fail_fast: true
repos:
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: ['--line-length', '120']
    files: '.+\.py$'
    always_run: false
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.9.3
  hooks:
  - id: isort
    args: []
    files: '.+\.py$'
    always_run: false
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: ['--config', 'setup.cfg']